Name=zero-lliurex-remote-agent
Name[es]=Instalador de LliureX RDesk
Name[ca_ES]=Instal·lador de LliureX RDesk
Name[ca@valencia]=Instal·lador de LliureX RDesk
Name[qcv]=Instal·lador de LliureX RDesk
Comment= Remote desktop application that allows two-way remote access between computers
Comment[es]=Aplicación de escritorio remoto que permite el acceso remoto bidireccional entre ordenadores
Comment[ca_ES]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Comment[ca@valencia]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Comment[qcv]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Icon=zero-lliurex-remote-agent
Category=Software
ScriptPath=zero-lliurex-remote-agent.zmd
Using=pkexec
Service=True
Locks=zero-lliurex-remote-agent
Groups=sudo;admins;teachers
Show=True
