Name=zero-lliurex-anydesk-client
Name[es]=Instalador de AnyDesk SAI
Name[ca_ES]=Instal·lador de AnyDesk SAI
Name[ca@valencia]=Instal·lador de AnyDesk SAI
Name[qcv]=Instal·lador de AnyDesk SAI
Comment=Remote desktop application that allows two-way remote access between computers
Comment[es]=Aplicación de escritorio remoto que permite el acceso remoto bidireccional entre ordenadores
Comment[ca_ES]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Comment[ca@valencia]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Comment[qcv]=Aplicació d'escriptori remot que permet l'accés remot bidireccional entre ordinadors
Icon=zero-lliurex-anydesk-client
Category=Software
ScriptPath=zero-lliurex-anydesk-client.zmd
Using=pkexec
Service=True
Locks=zero-lliurex-anydesk-client
Groups=sudo;admins;teachers
